steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'set', 'image', 'deployment/mydepl', 'my-image=gcr.io/kk-backend-418413/github.com/bogdansavel/kk-backend:$COMMIT_SHA' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/kk-backend-418413/github.com/bogdansavel/kk-backend:$COMMIT_SHA', 'build/libs/' ]