spring:
  config:
    import: "sm://"
  application:
    name: kkbackend
    secret:
      google-sheets: "${sm://projects/338111463629/secrets/google-sheets-secret}"
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gcp:
      sql:
        enabled: false