spring:
  config:
    import: "sm://"
  application:
    name: kkbackend
    secret:
      google-sheets: "${sm://projects/338111463629/secrets/google-sheets-secret}"
  datasource:
    url: jdbc:postgresql:///postgres?cloudSqlInstance=kk-backend-418413:europe-west1:kk-backend-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gcp:
      sql:
        enabled: false