spring:
  application.name: kkbackend
  datasource:
    url: "jdbc:postgresql://localhost:5432/compose-postgres"
    username: compose-postgres
    password: compose-postgres
  jpa:
    hibernate:
      ddl-auto: update

