spring:
  application:
    name: kkbackend
  datasource:
    url: jdbc:postgresql://dpg-csidkaij1k6c73ar9aig-a.frankfurt-postgres.render.com:5432/test
    username: admin
    password: NRNMRQyqgLjdW4pywTC3eJcyZO5zNrql
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

current-event: 70c164ab-30ac-4811-b879-116d56143e96
