spring:
  application:
    name: kkbackend
  datasource:
    url: jdbc:postgresql://dpg-csidkaij1k6c73ar9aig-a.frankfurt-postgres.render.com:5432/kk_db
    username: admin
    password: NRNMRQyqgLjdW4pywTC3eJcyZO5zNrql
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

current-event: d865698d-c496-4160-88bc-b607cfa91389
